CREATE TABLE transaction_types (
    id INTEGER PRIMARY KEY,
    type TEXT NOT NULL UNIQUE
);

INSERT INTO transaction_types (id, type) VALUES
    (1, 'INCOME'),
    (2, 'EXPENSES'),
    (3, 'TRANSFER');

CREATE TABLE categories (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

INSERT INTO categories (id, name) VALUES
    (1, 'comida'),
    (2, 'besteira'),
    (3, 'estudo'),
    (4, 'férias'),
    (5, 'transporte'),
    (6, 'moradia'),
    (7, 'saúde'),
    (8, 'lazer'),
    (9, 'contas'),
    (10, 'investimento'),
    (11, 'presente'),
    (12, 'outros');

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
    type INTEGER NOT NULL REFERENCES transaction_types (id),
    category_id INTEGER NOT NULL DEFAULT 12 REFERENCES categories (id),
    description TEXT,
    payment_method TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source_text TEXT NOT NULL
);

CREATE INDEX transactions_type_occurred_at_idx
    ON transactions (type, occurred_at DESC);

CREATE INDEX transactions_occurred_at_idx
    ON transactions (occurred_at DESC);
